name: deploy static website to non-prod

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: static-non-prod-360841
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS CREDENTIAL
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: npm ci
        run: npm run build
      - name: deploy files to bucket
        run: aws s3 cp public ${{ env.BUCKET_NAME }}/ --recursive --acl public-read
        